services:
    vich.custom.random_namer:
        class: VichImagineBundle\Upload\Naming\RandomNamer
        calls:
            - [ setContainer, [ '@service_container' ] ]

    vich.custom.directory_namer:
        class: VichImagineBundle\Upload\Naming\DirectoryNamer
        calls:
            - [ setContainer, [ '@service_container' ] ]

    vich.listener.upload:
        class: VichImagineBundle\EventListener\VichUploadListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: vich_uploader.post_upload, method: onPostUpload }

    vichimagine.uploader:
        class: VichImagineBundle\Upload\Upload
        arguments: ["@service_container"]

    vichimagine.file:
        class: VichImagineBundle\Upload\File
        arguments: ["@service_container"]

    # field